api/urls.py
from __future__ import annotations
from django.conf.urls import url
from debtagslayout.views import DebtagsTemplateView
from . import views

urlpatterns = [
    url(r'^$', DebtagsTemplateView.as_view(template_name='api/index.html'), name="api_index"),
    url(r'^patch', views.SubmitPatch.as_view(), name="api_patch"),
    url(r'^tag/search/(?P<query>[^/]+)?$', views.tag_search_view, name="api_tag_search"),
    url(r'^gitlab-vocabulary-pipeline-hook$', views.GitlabVocabularyPipeline.as_view(),
        name="api_gitlab_vocabulary_pipeline_hook"),

]

debtagsd/urls.py
from __future__ import annotations
from django.conf.urls import url, include
import django.conf.urls
from django.urls import path
from debtagslayout.views import DebtagsTemplateView
import debtagslayout.views
import reports.views as rviews
import django.contrib.auth.views as auth_views

django.conf.urls.handler403 = debtagslayout.views.Error403.as_view()
django.conf.urls.handler404 = debtagslayout.views.Error404.as_view()
django.conf.urls.handler500 = debtagslayout.views.Error500.as_view()

urlpatterns = [
    url(r'^robots.txt$', DebtagsTemplateView.as_view(template_name='robots.txt', content_type="text/plain"),
        name="root_robots_txt"),
    url(r'^$', DebtagsTemplateView.as_view(template_name='index.html'), name="root_index"),
    url(r'^license/$', DebtagsTemplateView.as_view(template_name='license.html'), name="root_license"),
    url(r'^doc/sso/$', DebtagsTemplateView.as_view(template_name='doc/sso.html'), name="root_doc_sso"),
    url(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='registration/login.html')),
    url(r'^accounts/logout/$', auth_views.LogoutView.as_view(next_page='/')),
    url(r'^api/', include("api.urls")),
    url(r'^rep/', include("reports.urls")),
    url(r'^reports/', include("reports.urls")),
    url(r'^exports/', include("exports.urls")),
    url(r'^edit/', include("editor.urls")),
    url(r'^search/', include("search.urls")),
    url(r'^getting-started/$', DebtagsTemplateView.as_view(template_name="reports/getting-started.html"),
        name="getting_started"),
    url(r'^statistics/$', rviews.Stats.as_view(), name="statistics"),
    path('signon/', include("signon.urls")),
    path('user/', include("user.urls")),
]

signon/urls.py
from django.urls import path
from . import views

app_name = "signon"

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('logout/<name>/', views.Logout.as_view(), name='logout_identity'),
    path('oidc/callback/<name>/', views.OIDCAuthenticationCallbackView.as_view(), name='oidc_callback'),
    path('whoami/', views.Whoami.as_view(), name='whoami'),
    path('link/<provider>/<int:pk>/', views.Link.as_view(), name='link'),
    path('unlink/<provider>/', views.Unlink.as_view(), name='unlink'),
]

user/urls.py
from __future__ import annotations
from django.urls import path
from debtagslayout.views import DebtagsTemplateView
from . import views

app_name = "user"

urlpatterns = [
    path(r'profile/', views.Profile.as_view(), name="profile"),
]

debtagslayout/models.py
from django.db import models

# Create your models here.

debtagslayout/views.py
from __future__ import annotations
import urllib.parse
from django.views.generic.base import TemplateView
from debtagslayout.mixins import DebtagsLayoutMixin
import logging

log = logging.getLogger(__name__)


class DebtagsTemplateView(DebtagsLayoutMixin, TemplateView):
    pass


class Error403(DebtagsLayoutMixin, TemplateView):
    def dispatch(self, *args, **kw):
        try:
            res = super().dispatch(*args, **kw)
            res.status_code = 403
            return res
        except Exception as e:
            log.error("403 view failed: %s", e, exc_info=e)
            raise

    def get_template_names(self):
        return [self.kwargs.get("template_name", "403.html")]


class Error404(DebtagsLayoutMixin, TemplateView):
    def dispatch(self, *args, **kw):
        try:
            res = super().dispatch(*args, **kw)
            res.status_code = 404
            return res
        except Exception as e:
            log.error("404 view failed: %s", e, exc_info=e)
            raise

    def get_template_names(self):
        return [self.kwargs.get("template_name", "404.html")]

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)

        exception_repr = self.kwargs["exception"].__class__.__name__
        # Try to get an "interesting" exception message, if any (and not the ugly
        # Resolver404 dictionary)
        try:
            message = self.kwargs["exception"].args[0]
        except (AttributeError, IndexError):
            pass
        else:
            if isinstance(message, str):
                exception_repr = message
        ctx['request_path'] = urllib.parse.quote(self.request.path)
        ctx['exception'] = exception_repr
        return ctx


class Error500(DebtagsLayoutMixin, TemplateView):
    def dispatch(self, *args, **kw):
        try:
            res = super().dispatch(*args, **kw)
            res.status_code = 500
            return res
        except Exception as e:
            log.error("500 view failed: %s", e, exc_info=e)
            raise

    def get_template_names(self):
        return [self.kwargs.get("template_name", "500.html")]

debtagslayout/templates/debtags-base.html
{% extends "debian-base.html" %}
{% load i18n %}

{% block title %}Debtags{% endblock %}

{% block head %}
{{block.super}}
<link rev="made" href="mailto:enrico@debian.org">
<meta name="Language" content="English">
<meta name="Author"    content="Enrico Zini, enrico@debian.org">
<link type="text/css" rel="stylesheet" media="all" href="{{ STATIC_URL }}css/debtags.css" />
{% endblock %}

{% block nav_searchbox %}
  <form name="begin" method="get" class="form-inline" action="{% url "editor_index" %}">
    <input type="text" name="pkg" id="pkg" class="form-control mr-2" placeholder="Package name">
    <button type="submit" class="btn btn-primary">{% trans "Tag" %}</button>
  </form>
{% endblock %}

{% block nav_user %}
<ul class="navbar-nav ml-2">
  {% if user.is_authenticated %}
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="fa fa-user-circle"></span>
      {{user.username}}
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="{% url "report_maint" email=user.get_maintainer_email %}"><span class="fa fa-cube"></span> {% trans "Packages" %}</a>
      <a class="dropdown-item" href="{% url "user:profile" %}"><span class="fa fa-user"></span> {% trans "Settings" %}</a>
      <a class="dropdown-item" href="{% url "signon:login" %}"><span class="fa fa-sign-in"></span> {% trans "Logins" %}</a>
      <form class="form-inline" method="POST" action="{% url "signon:logout" %}">{% csrf_token %}
        <input type="hidden" name="next" value="{% url 'root_index' %}">
        <button class="btn btn-link dropdown-item" method="submit"><span class="fa fa-sign-out"></span> {% trans "Logout" %}</button>
      </form>
    </div>
  </li>
  {% else %}
  <li class="nav-item">
    <a class="nav-link" href="{% url "signon:login" %}"><span class="fa fa-sign-in"></span> {% trans "Login" %}</a>
  </li>
  {% endif %}
</ul>
{% endblock %}

{% block navbar %}
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      About Debtags
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="{% url "root_index" %}">Main page</a>
      <a class="dropdown-item" href="https://wiki.debian.org/Debtags">Documentation</a>
      <a class="dropdown-item" href="https://wiki.debian.org/Debtags/FAQ">FAQ</a>
      <a class="dropdown-item" href="{% url "statistics" %}">Statistics</a>
    </div>
  </li>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Contribute
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="{% url "getting_started" %}">Getting started</a>
      {% if user.is_authenticated %}
      <a class="dropdown-item" href="{% url "report_maint" email=user.username %}">Tag your packages</a>
      {% endif %}
      <a class="dropdown-item" href="{% url "report_todo" %}">TODO list</a>
      <a class="dropdown-item" href="{% url "editor_index" %}">Tag editor</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url "report_index" %}">All reports</a>

    </div>
  </li>

  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Develop
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="{% url "api_index" %}">Site API</a>
      <a class="dropdown-item" href="{% url "exports_index" %}">Export data</a>
    </div>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{% url "search_packages" %}">Search</a>
  </li>
{% endblock %}

{% block footer %}
<div class="card-body">
<p>Copyright © 2011-2013 Enrico Zini &lt;enrico@debian.org&gt;. See <a href="{% url "root_license" %}">license terms</a>.
Source code is <a href="https://salsa.debian.org/debtags-team/debtagsd">available</a>.</p>
<p>Debtags is part of <a href="https://www.debian.org/">Debian</a>.</p>
</div>
{% endblock %}

debtagslayout/templates/debtags-pkginfo-light.html
<div class="pkginfo">
  <a href='{% url "editor_edit" name=pkg.name %}'>{{pkg.name}}<a> -- <span class="sdesc">{{pkg.sdesc}}</span>
</div>

debtagslayout/templates/debtags-pkginfo.html
<div class="pkginfo {{class}}">
  <div class="thumb">
    <a href="https://screenshots.debian.net/package/{{pkg.name}}">
        <img src="https://screenshots.debian.net/thumbnail/{{pkg.name}}"
             alt="screenshot">
    </a>
  </div>
  <ul class="links">
      {% if pkg.source != pkg.name %}
      <li class="source">Source: <b>{{pkg.source}}</b></li>
      {% endif %}
      <li><a href="{% url "report_pkginfo" pkg.name %}">[more info]</a></li>
      <li><a href="{% url "editor_edit" name=pkg.name %}">[tag editor]</a></li>
      <li><a href="https://packages.qa.debian.org/{{pkg.source}}">[PTS]</a></li>
      <li><a href="https://qa.debian.org/cgi-bin/dcontrol?package={{pkg.name}}&version={{pkg.version}}">debian/control</a></li>
  </ul>
  <a class="name" href="https://packages.debian.org/{{pkg.name}}">{{pkg.name}}</a>
  <span class="sep">-</span>
  <span class="sdesc">{{pkg.sdesc}}</span>
  <span class="ldesc">{{pkg.ldesc_html|safe}}</span>
</div>

debtagslayout/templates/debtags-settings.html
<div class="modal" tabindex="-1" role="dialog" id="dui-settings">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Settings</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h2>Distributions.</h2>

        <ul id="hide-dists">
            <li>
                <input type="checkbox" id="dui-settings-debian"></input>
                <label for="dui-settings-debian">Debian</label>
                <ul>
                    <li>
                        <input type="checkbox" id="dui-settings-debian-stable"></input>
                        <label for="dui-settings-debian-stable">Stable</label>
                    </li>
                    <li>
                        <input type="checkbox" id="dui-settings-debian-testing"></input>
                        <label for="dui-settings-debian-testing">Testing</label>
                    </li>
                    <li>
                        <input type="checkbox" id="dui-settings-debian-sid"></input>
                        <label for="dui-settings-debian-sid">Unstable</label>
                    </li>
                </ul>
            </li>
            <li>
                <input type="checkbox" id="dui-settings-ubuntu"></input>
                <label for="dui-settings-ubuntu">Ubuntu</label>
                <ul>
                    <li>
                        <input type="checkbox" id="dui-settings-ubuntu-lucid"></input>
                        <label for="dui-settings-ubuntu-lucid">Lucid</label>
                    </li>
                    <li>
                        <input type="checkbox" id="dui-settings-ubuntu-maverick"></input>
                        <label for="dui-settings-ubuntu-maverick">Maverick</label>
                    </li>
                    <li>
                        <input type="checkbox" id="dui-settings-ubuntu-natty"></input>
                        <label for="dui-settings-ubuntu-natty">Natty</label>
                    </li>
                    <li>
                        <input type="checkbox" id="dui-settings-ubuntu-oneiric"></input>
                        <label for="dui-settings-ubuntu-oneiric">Oneiric</label>
                    </li>
                    <li>
                        <input type="checkbox" id="dui-settings-ubuntu-precise"></input>
                        <label for="dui-settings-ubuntu-precise">Precise</label>
                    </li>
                </ul>
            </li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="dui-settings-save">Save changes</button>
      </div>
    </div>
  </div>
</div>